import { useSubmission } from "../hooks/useSubmission";
import { useState } from "react";
import type { FormEvent } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { ArrowRight, CalendarDays, ChevronRight, Plus, UsersRound, UserPlus } from "lucide-react";
import { useAuth } from "../hooks/useAuth";
import { useResource } from "../hooks/useResource";
import { post } from "../services/api";
import type { Activity, Group } from "../types";
import { dateLabel, timeLabel } from "../utils/format";
import { Avatar, Empty, ErrorState, FormError, Geometry, Heading, Loading, LoadingLabel } from "../components/UI";
import BalancePanel from "../components/BalancePanel";
import { useUnsavedChanges } from "../hooks/useUnsavedChanges";

export function GroupsPage() {
    const { data, loading, error, reload } = useResource<{ groups: Group[] }>("/groups");
    const { user } = useAuth(); const [search] = useSearchParams();
    return <div className="page"><div className="mobile-brand"><span>Después Dividimos</span><Link to="/profile" aria-label="Mi perfil"><Avatar name={user?.nombre || ""} small /></Link></div><Heading title="Mis grupos" subtitle={search.get("choose") === "expense" ? "Elegí un grupo y después la actividad donde querés registrar el gasto." : "Los buenos planes se comparten."} action={<Link className="icon-button filled" to="/groups/new" aria-label="Nuevo grupo"><Plus size={23} /></Link>} />{loading ? <Loading /> : error ? <ErrorState message={error} retry={reload} /> : !data?.groups.length ? <Empty title="Tu próximo plan empieza acá." text="Creá un grupo para ese viaje, juntada o salida. Después, invitá a los tuyos."><Link className="button" to="/groups/new"><Plus size={18} />Crear mi primer grupo</Link></Empty> : <div className="group-grid">{data.groups.map((group, index) => <Link to={`/groups/${group.id}`} key={group.id} className={"group-card " + (index % 3 === 0 ? "dark-surface" : "light-surface")}><Geometry /><div className="group-card-content"><span className="group-symbol"><UsersRound size={22} strokeWidth={1.5} /></span><h2>{group.nombre}</h2><p>Un espacio para compartir</p><footer><span>Desde {dateLabel(group.createdAt).toLowerCase()}</span><ArrowRight size={21} /></footer></div></Link>)}<Link className="new-group-card" to="/groups/new"><span><Plus size={25} /></span><strong>¿Un nuevo plan?</strong><p>Creá otro grupo</p></Link></div>}<div className="home-note"><span className="short-line" /><p>Disfrutá ahora.<br /><strong>Después dividimos.</strong></p></div></div>;
}
export function NewGroupPage() {
    const [search] = useSearchParams(); const mode = search.get("mode"); const trip = mode === "trip";
    const navigate = useNavigate(); const [nombre, setNombre] = useState(""); const { busy, begin, end } = useSubmission(); const [error, setError] = useState("");
    const guard = useUnsavedChanges(Boolean(nombre));
    async function submit(e: FormEvent) { e.preventDefault(); if (!begin()) return; if (!nombre.trim()) { setError("Ingresá un nombre para el grupo."); end(); return; }  setError(""); try { const { newGroup } = await post<{ newGroup: Group }>("/groups", { nombre: nombre.trim() }); guard.allow(); navigate(`/groups/${newGroup.id}?created=${mode || "group"}`); } catch (err) { setError((err as Error).message); } finally { end(); } }
    return <div className="page narrow">{guard.dialog}<Heading title={trip ? "Crear viaje" : "Crear grupo"} back="/home" subtitle={trip ? "Un lugar para todos los días y las cuentas del viaje." : "Primero, reuní a las personas con las que compartís."} /><div className="form-intro light-surface"><Geometry /><UsersRound size={30} /><p>El plan lo ponen ustedes.<br /><strong>Las cuentas quedan acá.</strong></p></div><form onSubmit={submit}><fieldset disabled={busy}><label>Nombre del grupo<input autoFocus required maxLength={120} placeholder="Ej: Viaje a Brasil" value={nombre} onChange={(e) => setNombre(e.target.value)} /></label><p className="field-help">Después invitá a tus compañeros. Las fechas se eligen al agregar cada actividad.</p><FormError message={error} /><button className="button full-width" type="submit">{busy ? <LoadingLabel text="Creando…" /> : trip ? "Crear viaje" : "Crear grupo"}<ArrowRight size={18} /></button></fieldset></form></div>;
}
function Activities({ groupId }: { groupId: string }) {
    const [filter, setFilter] = useState("");
    const { data, loading, error, reload } = useResource<{ activities: Activity[] }>(`/groups/${groupId}/activities${filter ? "/" + filter : ""}`);
    const ordered = [...(data?.activities || [])].sort((a, b) => filter === "history" ? b.startAt.localeCompare(a.startAt) : a.startAt.localeCompare(b.startAt));
    return <><div className="section-toolbar"><div className="filter-pills" aria-label="Filtrar actividades">{[["", "Todas"], ["upcoming", "Próximas"], ["history", "Historial"]].map(([value, label]) => <button key={value} aria-pressed={filter === value} onClick={() => setFilter(value)}>{label}</button>)}</div><Link className="text-link desktop-only" to={`/groups/${groupId}/activities/new`}><Plus size={17} />Nueva actividad</Link></div>{loading ? <Loading /> : error ? <ErrorState message={error} retry={reload} /> : !ordered.length ? <Empty title={filter === "upcoming" ? "Todavía no hay próximos planes." : filter === "history" ? "La historia recién empieza." : "¿Qué van a hacer?"} text="Creá una actividad y elegí quiénes participan. Cada plan tiene sus propias cuentas."><Link className="button" to={`/groups/${groupId}/activities/new`}><Plus size={18} />Crear actividad</Link></Empty> : <div className="activity-list">{ordered.map((activity, index) => <div key={activity.id}>{(index === 0 || new Date(ordered[index - 1].startAt).toDateString() !== new Date(activity.startAt).toDateString()) && <h3 className="day-heading">{dateLabel(activity.startAt)}</h3>}<Link className="activity-card" to={`/activities/${activity.id}`} key={activity.id}><span className="list-icon"><CalendarDays size={22} /></span><div className="list-body"><strong>{activity.nombre}</strong><p>{dateLabel(activity.startAt)} · {timeLabel(activity.startAt)}</p><div className="avatar-stack">{activity.participantes.slice(0, 4).map((p) => <Avatar small key={p.usuario.id} name={p.usuario.nombre} />)}<span>{activity.participantes.length} {activity.participantes.length === 1 ? "participante" : "participantes"}</span></div></div><ChevronRight size={19} /></Link></div>)}</div>}<Link className="floating-action" to={`/groups/${groupId}/activities/new`}><Plus size={20} />Nueva actividad</Link></>;
}
export function GroupPage() {
    const { groupId = "" } = useParams(); const [search, setSearch] = useSearchParams(); const tab = search.get("tab") === "balance" ? "balance" : "activities";
    const { data, loading, error, reload } = useResource<{ group: Group }>(`/groups/${groupId}`);
    if (loading) return <div className="page"><Loading /></div>;
    if (error) return <div className="page"><Heading title="Grupo" back="/groups" /><ErrorState message={error} retry={reload} /></div>;
    if (!data) return null;
    const group = data.group;
    return <div className="context-page"><section className="context-hero dark-surface"><Geometry /><div className="hero-top"><Link to="/groups" className="icon-button" aria-label="Volver a mis grupos"><ChevronRight className="rotate-180" /></Link><Link to={`/groups/${groupId}/invite`} className="text-link"><UserPlus size={19} />Invitar</Link></div><p className="eyebrow">NUESTRO GRUPO</p><h1>{group.nombre}</h1><p className="hero-subtitle">{group.miembros?.length} personas · muchos planes por compartir</p><div className="hero-members">{group.miembros?.map((m) => <Avatar key={m.id} name={m.nombre} />)}<Link className="avatar avatar-add" to={`/groups/${groupId}/invite`} aria-label="Invitar al grupo"><Plus size={18} /></Link></div></section><section className="context-body"><div className="tabs" aria-label="Secciones del grupo"><button aria-pressed={tab === "activities"} onClick={() => setSearch({})}>Actividades</button><button aria-pressed={tab === "balance"} onClick={() => setSearch({ tab: "balance" })}>Balance del grupo</button></div><div className="context-content">{search.has("created") && <div className="onboarding" role="status"><h2>{group.nombre} está listo.</h2><p>1 ✓ Crear grupo · 2 Invitar personas · 3 Agregar el primer plan</p><Link className="text-link" to={`/groups/${groupId}/invite`}>Invitar personas →</Link><Link className="text-link" to={`/plans/new?group=${groupId}`}>Crear un plan →</Link></div>}{group.miembros?.length === 1 && <p className="companion-note">Los planes son mejores acompañados. <Link to={`/groups/${groupId}/invite`}>Invitá a las personas con las que vas a compartir gastos.</Link></p>}{tab === "balance" ? <BalancePanel path={`/groups/${groupId}/balance`} /> : <Activities groupId={groupId} />}</div></section></div>;
}
export function InvitePage() {
    const { groupId } = useParams(); const [email, setEmail] = useState(""); const { busy, begin, end } = useSubmission(); const [error, setError] = useState(""); const [success, setSuccess] = useState(false);
    const guard = useUnsavedChanges(Boolean(email));
    async function submit(e: FormEvent) { e.preventDefault(); if (!begin()) return;  setError(""); setSuccess(false); try { await post(`/groups/${groupId}/invitations`, { email: email.trim() }); setSuccess(true); setEmail(""); } catch (err) { setError((err as Error).message); } finally { end(); } }
    return <div className="page narrow">{guard.dialog}<Heading title="Sumá a los tuyos" subtitle="Invitá a alguien que ya tenga una cuenta." back={`/groups/${groupId}`} /><form onSubmit={submit}><fieldset disabled={busy}><label>Email de la persona<input type="email" autoComplete="off" autoFocus required placeholder="nombre@email.com" value={email} onChange={(e) => setEmail(e.target.value)} /></label><p className="field-help">La invitación aparecerá en su sección Invitaciones. No se envía un email.</p><FormError message={error} />{success && <p className="success-note" role="status">Invitación enviada. Ya puede aceptarla desde su cuenta.</p>}<button className="button full-width">{busy ? <LoadingLabel text="Enviando…" /> : "Enviar invitación"}<UserPlus size={18} /></button></fieldset></form></div>;
}
